<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>MistikLauncher</AssemblyName>
    <ApplicationIcon>mistik_icon.ico</ApplicationIcon>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Version>5.0.0.0</Version>
    <AssemblyVersion>5.0.0.0</AssemblyVersion>
    <FileVersion>5.0.0.0</FileVersion>
    <Authors>Mustafa</Authors>
    <Company>Mustafa Developer</Company>
    <Product>Mistik Launcher</Product>
    <Copyright>Copyright © 2026 Mustafa. Tüm Hakları Saklıdır.</Copyright>
    <Description>Kendi bilgisayarınızda tek tıkla yüksek performanslı Minecraft sunucuları kurun, yönetin ve tünelleme ile arkadaşlarınızla paylaşın.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.VisualBasic" Version="10.3.0" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3967.48" />
    <PackageReference Include="MQTTnet" Version="4.3.7.1207" />
    <PackageReference Include="MQTTnet.Extensions.ManagedClient" Version="4.3.7.1207" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\auto-mcs.exe" />
  </ItemGroup>
</Project>
